In [2]:
import numpy as np
a=np.array([1,2,3])
print(a)
b=np.array([[1,2,3,],[4,5,6]],dtype='int16')

[1 2 3]


In [3]:
a.ndim


1

In [3]:
b.ndim
b.shape
a.dtype


dtype('int32')

In [4]:
b.dtype
b.itemsize
b.nbytes

12

In [5]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a[1,2]
a[:,3]
a[1,:]
a[0,1:6:2]
a[1,5]=20
print(a)



[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [6]:
#3d example
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print (b)
b[0,1,1]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


4

In [7]:
b[:,1,:]
np.zeros((2,3))
np.ones((2,3,2))
np.full((2,2),99)
np.random.rand(4,2)
np.random.randint(8,size=(3,3))

array([[7, 4, 7],
       [2, 0, 7],
       [5, 0, 2]])

In [11]:
arr=np.array([[1,2,3]])
        
r1=np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [16]:
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)
output[1:4,1:4]=z
print (output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
a=np.array([1,2,3])
a+2
a*2
a/2

array([0.5, 1. , 1.5])

b=np.array([4,5,6])
a+b

##### Linear Algebra


In [32]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
c=np.matmul(a,b)
print (c)
##np.linalg.det(b)#error =must be square matrix


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [27]:
c=np.identity(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
np.linalg.det(c)

1.0

In [37]:
stats=np.array([[1,2,3],[4,5,6]])
print(np.min(stats))
print(np.max(stats,axis=1))
np.sum(stats,axis=0)


1
[3 6]


array([5, 7, 9])

In [39]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [44]:
filedata=np.genfromtxt('data.txt',delimiter=',')
filedata>5

array([[False, False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [45]:
filedata[filedata>5]

array([ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 14., 15., 16., 17.,
       18., 19., 20.])

In [46]:
((filedata>50)&(filedata<100))

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])